services:
  postgresql:
    image: postgres:latest
    container_name: ataccoteque-postgresql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - ataccoteque-network

  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: ataccoteque-meilisearch
    restart: always
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_ENV: production
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - ataccoteque-network

  backend:
    build:
      context: ./app/server
      dockerfile: Dockerfile
    container_name: ataccoteque-backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql:5432/${POSTGRES_DB}?schema=public
      MEILI_HOST: http://meilisearch:7700
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - meilisearch
      - postgresql
    networks:
      - ataccoteque-network

  frontend:
    build:
      context: ./app/client
      dockerfile: Dockerfile
      args:
        VITE_API_ENDPOINT: /api
    container_name: ataccoteque-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - ataccoteque-network

  nginx:
    image: nginx:alpine
    container_name: ataccoteque-nginx
    restart: always
    ports:
      - "8099:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./files:/var/www/files:ro
    depends_on:
      - frontend
      - backend
    networks:
      - ataccoteque-network

volumes:
  meilisearch_data:
  postgresql_data:

networks:
  ataccoteque-network:
    driver: bridge
